### ISSUE TITLE
Asset creation for Mastery indicator

### ISSUE THREAD

**Issue by josh-wassum** [josh-wassum/Study-Flashcards#23]
Need to generate some assets to show mastery.

**Comment by Minimistro32** [comment]
Tentative image assets for mastery screen:
![Moon](https://user-images.githubusercontent.com/65469567/157166130-3de465da-de10-44f3-8c09-e463d3c6224f.jpeg)
![Transparent Rocket](https://user-images.githubusercontent.com/65469567/157166131-9fc01b92-7b15-4965-b4cd-2d0a6a853c05.jpeg)

**Comment by Minimistro32** [comment]
![Moon](https://user-images.githubusercontent.com/65469567/157167039-b139645a-b400-46a9-b59f-a5f9221fdd6c.svg)
![rocket-ship-png-hd-rocket-space-ship-space-launch-propulsion-749](https://user-images.githubusercontent.com/65469567/157167042-a9cf6cb5-7dbe-486c-9c9d-d71f458901fd.png)
